BEGIN TRANSACTION;
INSERT INTO bookmark_groups
(id, name, emphasized, description, sort_order)
VALUES
(0, "应用", true, "", 0),
(1, "资讯", false, "", 1),
(2, "软件", false, "", 2),
(3, "开发", false, "", 3),
(4, "搜索", false, "", 4),
(5, "资源", false, "", 5),
(6, "影音", false, "", 6),
(7, "GPT", false, "", 7),
(8, "域", false, "", 8),
(9, "机场", false, "", 9),
(10, "破解", false, "", 10),
(11, "工具", false, "", 11),
(12, "SR6", false, "", 12),
(13, "素材", false, "", 13),
(14, "AI创作", false, "", 14);
INSERT INTO bookmarks
(group_id, name, href, icon, description, sort_order)
VALUES
(0, "Openwrt", "https://openwrt.meow/", "network", "网关", 0),
(0, "J4125", "https://j4125.meow:8006/", "server", "J4125 PVE 主机", 1),
(0, "Z1G5", "https://z1g5.meow:8006/", "hard-drive", "网络附加存储", 2),
(0, "Docker", "https://docker.meow/", "container", "Docker 容器管理", 3),
(0, "Bitwarden", "https://password.meow/", "vault", "Bitwarden 密码管理", 4),
(0, "Database", "http://database.meow/", "database", "数据库", 5),
(0, "Graphql", "http://graphql.meow/console", "database-search", "Graphql 查询", 6),
(0, "Memos", "http://memos.meow/", "notebook", "笔记", 7),
(0, "File", "http://file.meow/", "folder-bookmark", "配置文件", 8),
(0, "Navidrome", "http://music.meow/", "music", "本地音乐", 9),
(0, "AutoBangumi", "http://bangumi.meow/", "monitor-down", "自动追番", 10),
(0, "Jellyfin", "http://jellyfin.meow:8096/", "video", "观影", 11),
(0, "qBittorrent", "http://qbte.meow/", "magnet", "qB 下载", 12),
(0, "AriaNg", "http://ariang.meow/", "cloud-download", "Aria2 下载", 13),
(0, "Openlist", "http://openlist.meow/", "cloud-cog", "网盘聚合", 14),
(0, "BaiduYun", "http://baiduyun.meow/", "cloud-download", "百度网盘下载", 15),
(0, "ItTools", "http://ittools.web.meow/", "tool-case", "工具箱", 16),
(0, "Webp2jpg", "http://webp2jpg.web.meow/", "images", "图片转换", 17),
(0, "Vtracer", "http://vtracer.web.meow/", "vector-polygon", "位图转矢量图", 18),
(0, "Komga", "http://comic.meow/", "book-image", "漫画管理", 19),
(0, "RSS", "https://rss.meow/", "rss", "Rss 阅读器", 20),
(0, "ApiGate", "http://newapi.meow/", "share-2", "LLM API 网关", 21),
(0, "QDToday", "http://qdtoday.meow/", "list-checks", "定时任务", 22),
(0, "AstrBot", "http://astrbot.meow:6185/", "telescope", "Astr酱", 23),
(0, "Email", "https://email.eroneko.eu.org/", "mail", "域名邮箱", 24),
(0, "Blog", "https://eroneko.eu.org/", "square-text", "个人博客", 25),
(1, "绅士仓库", "https://cangku.moe/", "package-2", "", 0),
(1, "灵梦御所", "https://blog.reimu.net/", "paper-bag", "", 1),
(1, "琉璃神社", "https://www.hacg.mov/wp/", "hospital", "", 2),
(1, "JavBus", "https://www.javbus.com/forum/", "bus", "", 3),
(1, "Github 周刊", "https://github.com/OpenGithubs/github-weekly-rank", "newspaper", "", 4),
(2, "HelloWindows", "https://hellowindows.cn/", "grid-2x2", "", 0),
(2, "NextITellYou", "https://next.itellyou.cn/Original/", "grid-2x2", "", 1),
(2, "ImmortalWrt", "https://firmware-selector.immortalwrt.org/", "router", "", 2),
(2, "Greasy Fork", "https://greasyfork.org/zh-CN", "utensils", "", 3),
(3, "FreeForDev", "https://free-for.dev/", "circle-dollar-sign", "", 0),
(3, "Linux 命令文档", "https://wangchujiang.com/linux-command/", "file-text", "", 1),
(3, "Rust 文档", "https://kaisery.github.io/trpl-zh-cn/", "file-text", "", 2),
(3, "Hacking C++", "https://hackingcpp.com/", "file-text", "", 3),
(4, "漫喵动漫", "https://comicat.org/", "magnet", "", 0),
(4, "蜜柑计划", "https://mikanani.me/", "rss", "", 1),
(4, "FOFA", "https://fofa.info/", "search", "", 2),
(4, "Btdigg", "https://btdig.com/", "magnet", "", 3),
(4, "Torrentkitty", "https://www.torrentkitty.tv/", "magnet", "", 4),
(5, "東京図書館", "https://tokyotosho.org/", "library-big", "", 0),
(5, "Nyaa", "https://sukebei.nyaa.si/", "magnet", "", 1),
(5, "ExHentai", "https://exhentai.org/", "book-image", "", 2),
(5, "Kemono", "https://kemono.cr/", "image", "", 3),
(5, "Coomer", "https://coomer.cr/", "video", "", 4),
(5, "梓澪の妙妙屋", "https://zi0.cc/", "cloud", "", 5),
(6, "ACG漫音社", "https://www.acgjc.com/", "music", "", 0),
(6, "ASMR Online", "https://www.asmr.one/", "music", "", 1),
(6, "無料エロ動画保存", "https://truvaze.com/zh-CN", "video", "", 2),
(7, "秘塔", "https://metaso.cn/", "scan-search", "", 0),
(7, "Chatgpt", "https://chatgpt.com/", "brain-circuit", "", 1),
(7, "Gemini", "https://gemini.google.com/", "brain-circuit", "", 2),
(7, "DeepSeek", "https://chat.deepseek.com/", "brain-circuit", "", 3),
(7, "扣子空间", "https://space.coze.cn", "workflow", "", 4),
(8, "EU.org 域名", "https://nic.eu.org/arf/en/", "server-cog", "", 0),
(8, "Cloudflare", "https://dash.cloudflare.com/", "cloudy", "", 1),
(9, "Yahaha", "https://www.yahaha.one/", "plane", "", 0),
(9, "一元机场", "https://xn--4gq62f52gdss.com/", "plane", "", 1),
(9, "赔钱机场", "https://pqjc.site/", "plane", "", 2),
(10, "ManifestHub", "https://github.com/SteamAutoCracks/ManifestHub", "key", "", 0),
(10, "菜玩社区", "https://caigamer.cn/forum-1-1.htm?orderby=tid&digest=0", "file-key", "", 1),
(10, "JetBrains keys", "https://3.jetbra.in/", "key", "", 2),
(11, "Vmail", "https://vmail.dev/", "mail", "", 0),
(11, "RegExr", "https://regexr-cn.com/", "regex", "", 1),
(11, "轻小说机翻机器人", "https://n.novelia.cc/", "bot", "", 2),
(12, "EroScripts", "https://discuss.eroscripts.com/", "scroll-text", "", 0),
(12, "Ayva Stroker Lite", "https://www.ayva-stroker-lite.io/", "hand-grab", "", 1),
(12, "mosa", "https://trymosa.netlify.app/", "hand-grab", "", 2),
(13, "Simple Icons", "https://simpleicons.org/", "box", "", 0),
(13, "Tabler Icons", "https://tabler.io/icons", "box", "", 1),
(14, "Civitai", "https://civitai.red/", "file-box", "", 0),
(14, "玖帕喵", "https://jiupamiao.asia/market", "bot", "", 1),
(14, "标签超市", "https://tags.novelai.dev/", "tag", "", 2),
(14, "HuggingFace", "https://huggingface.co/", "face-slightly-smiling", "", 3),
(14, "AstrBot", "https://docs.astrbot.app/", "bot", "", 4)
COMMIT;